protein = [ 'ALA', 'ARG', 'ASN', 'ASP', 'CYS', 'GLN', 'GLU', 'GLY', 'HSD',
        'HSE', 'HSP', 'ILE', 'LEU', 'LYS', 'MET', 'PHE', 'PRO', 'SER', 'THR',
        'TRP', 'TYR', 'VAL', 'ALAD',
        ## 'CHO','EAM', # -- special formyl and 
        'HIS', 'MSE',
        # from Gromacs 4.5.3 oplsaa.ff/aminoacids.rtp
        'ARGN', 'ASPH', 'CYS2', 'CYSH', 'QLN', 'PGLU', 'GLUH', 'HIS1', 'HISD',
        'HISE', 'HISH', 'LYSH',
        # from Gromacs 4.5.3 gromos53a6.ff/aminoacids.rtp
        'ASN1', 'CYS1', 'HISA', 'HISB', 'HIS2',
        # from Gromacs 4.5.3 amber03.ff/aminoacids.rtp
        'HID', 'HIE', 'HIP', 'ORN', 'DAB', 'LYN', 'HYP', 'CYM', 'CYX', 'ASH',
        'GLH', 'ACE', 'NME',
        # from Gromacs 2016.3 amber99sb-star-ildn.ff/aminoacids.rtp
        'NALA', 'NGLY', 'NSER', 'NTHR', 'NLEU', 'NILE', 'NVAL', 'NASN', 'NGLN',
        'NARG', 'NHID', 'NHIE', 'NHIP', 'NTRP', 'NPHE', 'NTYR', 'NGLU', 'NASP',
        'NLYS', 'NPRO', 'NCYS', 'NCYX', 'NMET', 'CALA', 'CGLY', 'CSER', 'CTHR',
        'CLEU', 'CILE', 'CVAL', 'CASF', 'CASN', 'CGLN', 'CARG', 'CHID', 'CHIE',
        'CHIP', 'CTRP', 'CPHE', 'CTYR', 'CGLU', 'CASP', 'CLYS', 'CPRO', 'CCYS',
        'CCYX', 'CMET', 'CME', 'ASF',]
nucleotides = ['ADE','URA','CYT','GUA','THY','DA']
water_and_ion = ['SOD', 'CLA', 'TIP', 'TIP3', 'TIP4']

default_angles = ['psi', 'phi', 'omega']
X = {'GLY': ['psi', 'phi', 'omega'],
 'ALA': ['psi', 'phi', 'omega'],
 'SFO': ['psi', 'phi', 'omega'],
 'SER': ['psi', 'phi', 'omega', 'chi1'],
 'VAL': ['psi', 'phi', 'omega', 'chi1'],
 'THR': ['psi', 'phi', 'omega', 'chi1'],
 'CYS': ['psi', 'phi', 'omega', 'chi1'],
 'HSD': ['psi', 'phi', 'omega', 'chi1'],
 'PHE': ['psi', 'phi', 'omega', 'chi1', 'chi2'],
 'TYR': ['psi', 'phi', 'omega', 'chi1', 'chi2'],
 'TRP': ['psi', 'phi', 'omega', 'chi1', 'chi2'],
 'ASN': ['psi', 'phi', 'omega', 'chi1', 'chi2'],
 'ILE': ['psi', 'phi', 'omega', 'chi1', 'chi2'],
 'LEU': ['psi', 'phi', 'omega', 'chi1', 'chi2'],
 'ASP': ['psi', 'phi', 'omega', 'chi1', 'chi2'],
 'PRO': ['psi', 'phi', 'omega', 'chi1', 'chi2'],
 'GLU': ['psi', 'phi', 'omega', 'chi1', 'chi2', 'chi3'],
 'GLN': ['psi', 'phi', 'omega', 'chi1', 'chi2', 'chi3'],
 'MET': ['psi', 'phi', 'omega', 'chi1', 'chi2', 'chi3'],
 'LYS': ['psi', 'phi', 'omega', 'chi1', 'chi2', 'chi3', 'chi4'],
 'ARG': ['psi', 'phi', 'omega', 'chi1', 'chi2', 'chi3', 'chi4','chi5'],
 'DA' : ['alpha','beta','gamma','delta','epsilon','zeta','chi'],
 'DT' : ['alpha','beta','gamma','delta','epsilon','zeta','chi'],
 'DC' : ['alpha','beta','gamma','delta','epsilon','zeta','chi'],
 'DG' : ['alpha','beta','gamma','delta','epsilon','zeta','chi']}
 
chain_to_num = {'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}
